<?php

/**
 * This is the model base class for the table "test".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Test".
 *
 * Columns in table "test" available as properties of the model,
 * followed by relations of table "test" available as properties of the model.
 *
 * @property string $id
 * @property string $name
 * @property integer $is_reaction_test
 *
 * @property Question[] $questions
 * @property UserTest[] $userTests
 */
abstract class BaseTest extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'test';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Test|Tests', $n);
	}

	public static function representingColumn() {
		return 'name';
	}

	public function rules() {
		return array(
			array('name', 'required'),
			array('is_reaction_test', 'numerical', 'integerOnly'=>true),
			array('name', 'length', 'max'=>255),
			array('is_reaction_test', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, name, is_reaction_test', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'questions' => array(self::HAS_MANY, 'Question', 'test_id'),
			'userTests' => array(self::HAS_MANY, 'UserTest', 'test_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'name' => Yii::t('app', 'Name'),
			'is_reaction_test' => Yii::t('app', 'Is Reaction Test'),
			'questions' => null,
			'userTests' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id, true);
		$criteria->compare('name', $this->name, true);
		$criteria->compare('is_reaction_test', $this->is_reaction_test);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}